name = "irstreak-api"
main = "src/index.js"
compatibility_date = "2026-07-04"

[d1_databases]
DB = { binding = "DB", database_name = "irstreak", database_id = "1c809404-7c96-432c-b090-1e4786679a4b" }
# ... keep the rest of your observability settings ...

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1
