name = "irstreak"
main = "_worker.js"
compatibility_date = "2026-07-04"

# 1. Maps your frontend folder to the Workers Asset Engine
[assets]
directory = "./public"
binding = "ASSETS"

# 2. Binds your D1 Database securely using your unique ID
[[d1_databases]]
binding = "DB"
database_name = "irstreak" 
database_id = "1c809404-7c96-432c-b090-1e4786679a4b"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1
